name: deep-learning-template
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=10.2 # adjust or remove if on cpu
  - pytorch
  - torchvision
  - torchaudio
  - wandb
  - pytorch-lightning
  - click
  - autopep8
  - timm
  - typing

