name: deep-learning-template
channels:
  - conda-forge # prefer conda-forge for updated packages
  - pytorch
dependencies:
  - python=3.9
  - cudatoolkit=10.2 # adjust or remove if on cpu
  - pytorch
  - torchvision
  - click
  - autopep8
  - typing
  - pip
  - wandb
  - pytorch-lightning
  - timm
  # Use pip for packages that are outdated on conda-forge
  # - pip:



