name: deep-learning-template
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=10.2 # adjust or remove if on cpu
  - pytorch
  - torchvision
  - click
  - autopep8
  - typing
  - pip
  - pip:
    - wandb
    - pytorch-lightning
    - timm



